bangbangcon/bangbangcon.github.io

- 2014-transcripts/chloe-weil-tasty-stacks.txt
- 2014-transcripts/katherine-ye-proofs-about-programs-proofs-as-programs.txt
- 2014-transcripts/michael-arntzenius-continuations.txt
- 2014-transcripts/paul-khuong-lz77-refactors-program-traces.txt
- 2014-transcripts/travis-mcdemus-the-sound-of-segfaults.txt
I think the transcripts are great! I filled in some of the blanks marked "(inaudible)", using the audio recordings.
> Fill in some inaudible words in the transcripts

- 2015-speaker-materials/README.md
The slides are HTML, which may or may not work with your system. If they don't, that's okay :)
> Added my code and slides

- speakers.md
Figured after a year, it needed some rewriting. 
It's been a long while since I've done a GitHub pull request. I hope this works! :smile:
> Revising text of synopsis and bio

- speakers.md
Shorten bio and add note about emoji compatibility
This completes the changes I plan to make to my !!con abstract before it goes live.
> Update my speaker info

- speakers.md
Scratch is accessible in the generic sense of the word, but I've sorta realised it's poor word choice, as I won't be talking about assistive technology or other common things.
> Speaker Update for tef

- 2016-speaker-materials/README.md
> Add link to Mariko's slide

- 2016-speaker-materials/README.md
Thanks for organizing this awesome conference! :)
> Add link to Anjana Vakil's slides

- 2016-speaker-materials/README.md
> fix link to Mark Dominus's slides

- 2016-speaker-materials/README.md
Add link to my blog post for "My favorite Unicode character: the zero width joiner!"
> add my talk materials

- sponsors.md
> Make Julia in charge of sponsorship

- sponsors.md
@jvns -- what do you think about this wording tweak?  cc @mrb
> Sponsors wording

- 2017-speaker-materials/README.md
Talk: Glk! A universal user interface! for interactive fiction!
> Added my talk (Andrew Plotkin)

- 2017-speaker-materials/README.md
> Add the slides for my talk

- speakers.md
This is a bit silly but I also think it's important for people to know what space disco is :smile:.
> speakers.md: link to some space disco

- speakers.md
> slight edit to abstract/bio

- program.md
Fix the table markdown syntax on the schedules.
cc/ @lkuper
> Fix markdown

- speakers.md
I overpromised some content ^_^
> Update Evy's abstract to be more accurate to the talk

- _layouts/default-2019.html
- index.md
> Correct small typo of 2019 dates

- speakers.md
Just noticed it said `Tic-ta"-toe` in one spot on the website.
> Fix a couple typos in talk description

- index.md
> Close 2020 CFP.

- conduct.md
- stylesheets/stylesheet.css
Although the commits happen to be mine, @jvns , @lkuper , and I have been working on this for a few years now.  Although I think there's always room for more tweaking on the wording, I'm happy with how this improves on our previous Code of Conduct.  Thanks also to @geekygirlsarah for additional feedback and copy-editing.
> The great Code-of-Conduct revamp!

- _layouts/default-2021.html
- give-a-talk.md
- index.md
Note that this is blocked on #141.
> Open the Call for Proposals!

- README.md
- _layouts/default-2020.html
- index.md
_current site_
_site after commit_
- fix issues with no language attribute set in html document
- fix issues with the hidden CSRF form not having a label (even though most site
users won't see this, having a label is still a good accessibility practice to
tell people using screen readers that they don't need to add anything in the
form
- add very basic readme in case others want to run the site locally and contribute
> address accessibility issues and add basic readme

- index.md
- program.md
- speakers.md
> Remove Peter Sobot
